### ISSUE TITLE
[Networking] Get remote shell into FCVM

### ISSUE THREAD

**Issue by MNThomson** [Project-Embr/embr#10]
## Implementation
Implement a method to gain a remote shell onto the running FCVM from the host machine (and from another machine also). This would be preferably an `SSH` connection, but is not the only option. This will facilitate clients to remotely connect to their personal FCVM's remotely.

## Currently Available
Currently the only way to interact with the FCVM is through the terminal that is running worker.

## Requires
Blocked by #6

**Comment by Redskulling** [comment]
It is possible to ssh into the VM by using the IP address from veth0.
