### ISSUE TITLE
[Worker] Run VM in background

### ISSUE THREAD

**Issue by MNThomson** [Project-Embr/embr#4]
When running the `worker` program, the created VM's should be in the background. Additionally, reconnecting to the instance and issuing additional commands with the Go SDK should still be possible.

**Comment by Addie-Finke** [comment]
Looking into the potential of spawning the vm inside of a go routine and using go's routine channel function to communicate commands to the vm, not sure if its gonna work yet.  Will look into implementation next week after my exams.

**Comment by Addie-Finke** [comment]
I want to do some testing to make sure the overhead wont be to high as well but from the research I have done routines have significantly lower overhead both for ITC and just general running then threads, and since we will only be having one routine for each VM the overhead should be fine.

**Comment by Addie-Finke** [comment]
Running into more computer issues, hoping to get it figured out soon but I have planned out a Go routine implementation and will get to testing it the second my computer is working again.  Have parts coming in on Wednesday so if all goes well ill get it up and running by EOD Thurs.
